name: Bug report
description: Something about the add-on does not work
labels: ["bug"]
body:
  - type: input
    id: version
    attributes:
      label: Add-on version
      placeholder: "1.1.1"
    validations:
      required: true
  - type: input
    id: ha
    attributes:
      label: Home Assistant version
      placeholder: "2026.8.3"
    validations:
      required: true
  - type: dropdown
    id: arch
    attributes:
      label: Architecture
      options: [aarch64, amd64]
    validations:
      required: true
  - type: textarea
    id: what
    attributes:
      label: What happened
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: Add-on log
      render: text
